version: '3.4'

services:
  identifier:
    image: semtech/mu-identifier:1.7.0
    links:
      - dispatcher:dispatcher
  dispatcher:
    image: semtech/mu-dispatcher:1.1.2
    links:
      - resource:resource
    volumes:
      - ./config/dispatcher:/config

  db:
    image: redpencil/virtuoso
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://mu.semte.ch/application"
    volumes:
      - ./data/db:/data
      - ./config/virtuoso/virtuoso.ini:/data/virtuoso.ini
  resource:
    image: semtech/mu-cl-resources:1.17.1
    links:
      - db:database
    volumes:
      - ./config/resources:/config

  harvester:
    image: semtech/repo-harvester
    links:
      - db:database
